insert into authors (first_name, last_name) values ('Drucie', 'Goodbourn');
insert into authors (first_name, last_name) values ('Marcia', 'Aggiss');
insert into authors (first_name, last_name) values ('Giovanni', 'Bigg');
insert into authors (first_name, last_name) values ('Duffie', 'Eynon');
insert into authors (first_name, last_name) values ('Anselma', 'McKennan');
insert into authors (first_name, last_name) values ('Gert', 'Kira');
insert into authors (first_name, last_name) values ('Clerc' , 'Djakovic');
insert into authors (first_name, last_name) values ('Stacee', 'Elsy');
insert into authors (first_name, last_name) values ('Dorotea', 'Bonhill');
insert into authors (first_name, last_name) values ('Minni', 'Bunney');
insert into authors (first_name, last_name) values ('Berty', 'Gandley');
insert into authors (first_name, last_name) values ('Raynard', 'Tesdale');
insert into authors (first_name, last_name) values ('Joanna', 'Hutfield');
insert into authors (first_name, last_name) values ('Dannie', 'Glidder');
insert into authors (first_name, last_name) values ('Timmie', 'Adshede');

insert into books (title, price_old, price, publish_date, author_id) values ('exploit real-time e-commerce', '$203.23', '$43.37', '02/02/1995', 1);
insert into books (title, price_old, price, publish_date, author_id) values ('utilize real-time interfaces', '$260.31', '$35.96', '08/08/1991', 2);
insert into books (title, price_old, price, publish_date, author_id) values ('extend strategic e-services', '$272.00', '$151.04', '03/25/2001', 3);
insert into books (title, price_old, price, publish_date, author_id) values ('iterate integrated solutions', '$271.58', '$141.40', '11/11/2006', 2);
insert into books (title, price_old, price, publish_date, author_id) values ('cultivate magnetic e-commerce', '$278.43', '$54.44', '12/01/2020', 1);
insert into books (title, price_old, price, publish_date, author_id) values ('chitect vertical ROI', '$282.54', '$102.61', '01/19/1952', 4);
insert into books (title, price_old, price, publish_date, author_id) values ('disintermediate extensible architectures', '$295.38', '$181.27', '06/02/2003', 5);
insert into books (title, price_old, price, publish_date, author_id) values ('extend leading-edge methodologies', '$283.08', '$97.96', '07/16/1992', 6);
insert into books (title, price_old, price, publish_date, author_id) values ('integrate one-to-one systems', '$258.51', '$52.25', '09/17/1964', 11);
insert into books (title, price_old, price, publish_date, author_id) values ('revolutionize 24/7 infrastructures', '$260.79', '$33.69', '12/03/2002', 3);
insert into books (title, price_old, price, publish_date, author_id) values ('enhance innovative e-services', '$256.54', '$160.98', '08/05/2010', 9);
insert into books (title, price_old, price, publish_date, author_id) values ('maximize 24/365 e-tailers', '$262.07', '$34.06', '04/16/2004', 8);
insert into books (title, price_old, price, publish_date, author_id) values ('scale integrated architectures', '$257.66', '$32.97', '10/29/2005', 8);
insert into books (title, price_old, price, publish_date, author_id) values ('e-enable frictionless web services', '$288.19', '$90.52', '06/07/2008', 9);
insert into books (title, price_old, price, publish_date, author_id) values ('strategize B2B channels', '$232.27', '$44.83', '06/03/1993', 7);
insert into books (title, price_old, price, publish_date, author_id) values ('syndicate compelling deliverables', '$287.45', '$101.89', '08/06/2015', 6);
insert into books (title, price_old, price, publish_date, author_id) values ('utilize bleeding-edge users', '$281.37', '$146.21', '08/23/1999', 5);