insert into books (title, priceOld, price) values ('exploit real-time e-commerce', '$203.23', '$43.37');
insert into books (title, priceOld, price) values ('utilize real-time interfaces', '$260.31', '$35.96');
insert into books (title, priceOld, price) values ('extend strategic e-services', '$272.00', '$151.04');
insert into books (title, priceOld, price) values ('iterate integrated solutions', '$271.58', '$141.40');
insert into books (title, priceOld, price) values ('cultivate magnetic e-commerce', '$278.43', '$54.44');
insert into books (title, priceOld, price) values ('chitect vertical ROI', '$282.54', '$102.61');
insert into books (title, priceOld, price) values ('disintermediate extensible architectures', '$295.38', '$181.27');
insert into books (title, priceOld, price) values ('extend leading-edge methodologies', '$283.08', '$97.96');
insert into books (title, priceOld, price) values ('integrate one-to-one systems', '$258.51', '$52.25');
insert into books (title, priceOld, price) values ('revolutionize 24/7 infrastructures', '$260.79', '$33.69');
insert into books (title, priceOld, price) values ('enhance innovative e-services', '$256.54', '$160.98');
insert into books (title, priceOld, price) values ('maximize 24/365 e-tailers', '$262.07', '$34.06');
insert into books (title, priceOld, price) values ('scale integrated architectures', '$257.66', '$32.97');
insert into books (title, priceOld, price) values ('e-enable frictionless web services', '$288.19', '$90.52');
insert into books (title, priceOld, price) values ('strategize B2B channels', '$232.27', '$44.83');
insert into books (title, priceOld, price) values ('syndicate compelling deliverables', '$287.45', '$101.89');
insert into books (title, priceOld, price) values ('utilize bleeding-edge users', '$281.37', '$146.21');
insert into books (title, priceOld, price) values ('cultivate 24/365 networks', '$270.99', '$184.76');
insert into books (title, priceOld, price) values ('embrace plug-and-play platforms', '$278.36', '$77.71');
insert into books (title, priceOld, price) values ('target innovative paradigms', '$298.94', '$130.01');
insert into books (title, priceOld, price) values ('generate open-source e-business', '$276.57', '$113.25');
insert into books (title, priceOld, price) values ('implement user-centric e-markets', '$254.70', '$115.31');
insert into books (title, priceOld, price) values ('utilize magnetic supply-chains', '$279.70', '$77.86');
insert into books (title, priceOld, price) values ('e-enable dot-com supply-chains', '$297.83', '$110.15');
insert into books (title, priceOld, price) values ('facilitate efficient eyeballs', '$232.30', '$131.48');

insert into authors (bookId, name) values (1,'Drucie Goodbourn');
insert into authors (bookId, name) values (2, 'Marcia Aggiss');
insert into authors (bookId, name) values (3, 'Giovanni Bigg');
insert into authors (bookId, name) values (4, 'Duffie Eynon');
insert into authors (bookId, name) values (5, 'Anselma McKennan');
insert into authors (bookId, name) values (6, 'Gert Kira');
insert into authors (bookId, name) values (7, 'Clerc Djakovic');
insert into authors (bookId, name) values (8, 'Stacee Elsy');
insert into authors (bookId, name) values (9, 'Dorotea Bonhill');
insert into authors (bookId, name) values (10, 'Minni Bunney');
insert into authors (bookId, name) values (11, 'Berty Gandley');
insert into authors (bookId, name) values (12, 'Raynard Tesdale');
insert into authors (bookId, name) values (13, 'Joanna Hutfield');
insert into authors (bookId, name) values (14, 'Dannie Glidder');
insert into authors (bookId, name) values (15, 'Timmie Adshede');
insert into authors (bookId, name) values (16, 'Fernando Neads');
insert into authors (bookId, name) values (17, 'Teddy Guilliland');
insert into authors (bookId, name) values (18, 'Paloma Grebert');
insert into authors (bookId, name) values (19, 'Kristos Usher');
insert into authors (bookId, name) values (20, 'Darcey Rohmer');
insert into authors (bookId, name) values (21, 'Cristie Isacsson');
insert into authors (bookId, name) values (22, 'Lindsay Coutthart');
insert into authors (bookId, name) values (23, 'Helyn Schneidar');
insert into authors (bookId, name) values (24, 'Bette-ann Askem');
insert into authors (bookId, name) values (25, 'Dom Robuchon');
