insert into authors (first_name, last_name) values ('Drucie', 'Goodbourn');
insert into authors (first_name, last_name) values ('Marcia', 'Aggiss');
insert into authors (first_name, last_name) values ('Giovanni', 'Bigg');
insert into authors (first_name, last_name) values ('Duffie', 'Eynon');
insert into authors (first_name, last_name) values ('Anselma', 'McKennan');
insert into authors (first_name, last_name) values ('Gert', 'Kira');
insert into authors (first_name, last_name) values ('Clerc' , 'Djakovic');
insert into authors (first_name, last_name) values ('Stacee', 'Elsy');
insert into authors (first_name, last_name) values ('Dorotea', 'Bonhill');
insert into authors (first_name, last_name) values ('Minni', 'Bunney');
insert into authors (first_name, last_name) values ('Berty', 'Gandley');
insert into authors (first_name, last_name) values ('Raynard', 'Tesdale');
insert into authors (first_name, last_name) values ('Joanna', 'Hutfield');
insert into authors (first_name, last_name) values ('Dannie', 'Glidder');
insert into authors (first_name, last_name) values ('Timmie', 'Adshede');
insert into authors (first_name, last_name) values ('Fernando', 'Neads');
insert into authors (first_name, last_name) values ('Teddy', 'Guilliland');
insert into authors (first_name, last_name) values ('Paloma', 'Grebert');
insert into authors (first_name, last_name) values ('Kristos', 'Usher');
insert into authors (first_name, last_name) values ('Darcey', 'Rohmer');
insert into authors (first_name, last_name) values ('Cristie', 'Isacsson');
insert into authors (first_name, last_name) values ('Lindsay', 'Coutthart');
insert into authors (first_name, last_name) values ('Helyn', 'Schneidar');
insert into authors (first_name, last_name) values ('Bette-ann', 'Askem');
insert into authors (first_name, last_name) values ('Dom', 'Robuchon');

insert into books (title, price_old, price, author_id) values ('exploit real-time e-commerce', '$203.23', '$43.37', 1);
insert into books (title, price_old, price, author_id) values ('utilize real-time interfaces', '$260.31', '$35.96', 2);
insert into books (title, price_old, price, author_id) values ('extend strategic e-services', '$272.00', '$151.04', 3);
insert into books (title, price_old, price, author_id) values ('iterate integrated solutions', '$271.58', '$141.40', 2);
insert into books (title, price_old, price, author_id) values ('cultivate magnetic e-commerce', '$278.43', '$54.44', 1);
insert into books (title, price_old, price, author_id) values ('chitect vertical ROI', '$282.54', '$102.61', 4);
insert into books (title, price_old, price, author_id) values ('disintermediate extensible architectures', '$295.38', '$181.27', 5);
insert into books (title, price_old, price, author_id) values ('extend leading-edge methodologies', '$283.08', '$97.96', 6);
insert into books (title, price_old, price, author_id) values ('integrate one-to-one systems', '$258.51', '$52.25', 11);
insert into books (title, price_old, price, author_id) values ('revolutionize 24/7 infrastructures', '$260.79', '$33.69', 3);
insert into books (title, price_old, price, author_id) values ('enhance innovative e-services', '$256.54', '$160.98', 9);
insert into books (title, price_old, price, author_id) values ('maximize 24/365 e-tailers', '$262.07', '$34.06', 8);
insert into books (title, price_old, price, author_id) values ('scale integrated architectures', '$257.66', '$32.97', 8);
insert into books (title, price_old, price, author_id) values ('e-enable frictionless web services', '$288.19', '$90.52', 9);
insert into books (title, price_old, price, author_id) values ('strategize B2B channels', '$232.27', '$44.83', 7);
insert into books (title, price_old, price, author_id) values ('syndicate compelling deliverables', '$287.45', '$101.89', 6);
insert into books (title, price_old, price, author_id) values ('utilize bleeding-edge users', '$281.37', '$146.21', 5);
insert into books (title, price_old, price, author_id) values ('cultivate 24/365 networks', '$270.99', '$184.76', 11);
insert into books (title, price_old, price, author_id) values ('embrace plug-and-play platforms', '$278.36', '$77.71', 10);
insert into books (title, price_old, price, author_id) values ('target innovative paradigms', '$298.94', '$130.01', 10);
insert into books (title, price_old, price, author_id) values ('generate open-source e-business', '$276.57', '$113.25', 12);
insert into books (title, price_old, price, author_id) values ('implement user-centric e-markets', '$254.70', '$115.31', 13);
insert into books (title, price_old, price, author_id) values ('utilize magnetic supply-chains', '$279.70', '$77.86', 1);
insert into books (title, price_old, price, author_id) values ('e-enable dot-com supply-chains', '$297.83', '$110.15', 2);
insert into books (title, price_old, price, author_id) values ('facilitate efficient eyeballs', '$232.30', '$131.48', 8);
