package org.makovej.bookshopapp.entities;

import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.persistence.*;
import java.util.List;

@Getter
@Setter
@Entity
@ApiModel(description = "Author Entity")
@Table(name = "authors", schema = "public")
@NoArgsConstructor
public class Author {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty(value = "author id generated by db", position = 2)
    private Long id;

    @ApiModelProperty(value = "author's name", example = "Jason Bee", position = 1)
    private String firstName;

    @Column(nullable = false)
    private String lastName;

    private String description;

    private String photo;

    @Override
    public String toString() {
        return firstName + " " + lastName;
    }

    @OneToMany(mappedBy = "author")
    @JsonIgnore
    private List<Book> bookList;

}
